module.exports = {
    phones: [{
            id: '1',
            image: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6316/6316066_sd.jpg;maxHeight=640;maxWidth=550',
            title: 'iPhone X',
            description: 'iPhone X features an all-screen design with a 5.8" Super Retina HD display with HDR and True Tone.¹ Designed with durable glass and a surgical-grade stainless steel band. Charges wirelessly.² Resists water and dust.³ 12.0MP dual cameras with dual optical image stabilization for great low-light photos. TrueDepth camera with Portrait selfies and new Portrait Lighting.⁴ Face ID lets you unlock and use Apple Pay with just a glance. Powered by A11 Bionic, the powerful and smart chip. Supports augmented reality experiences in games and apps. With iPhone X, the next era of iPhone has begun. SIM included in the box, not required for activation, will not lock to any carrier upon activation.',
            color: 'Silver',
            price: '$699.99',
            seller: 'Apple',
        },
        {
            id: '2',
            image: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6323/6323356_sd.jpg;maxHeight=640;maxWidth=550',
            title: 'Galaxy S10e',
            description: 'This Samsung Galaxy S10e features an immersive display, sleek in size and packed with power. The incredible, powerful camera and totally reimagined interface do more in less space, with an intelligent battery that`s big enough to share.',
            color: 'Prism Blue',
            price: '$699.99',
            seller: 'Samsung',
        },
        {
            id: '3',
            image: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6324/6324277_sd.jpg;maxHeight=640;maxWidth=550',
            title: 'Moto G7',
            description: 'Take fantastic photos with this unlocked Motorola Moto G7 smartphone. The 12.0-megapixel dual-lens camera with high-resolution zoom lets you capture clear, detailed subjects, and the 6.2-inch Full HD+ display provides immersive ultrawide viewing. Use the screen flash of this 64GB Motorola Moto G7 smartphone to take better, brighter front-camera selfies.',
            color: 'Ceramic Black',
            price: '$199.99',
            seller: 'Motorola',
        },
        {
            id: '4',
            image: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6305/6305718_sd.jpg;maxHeight=640;maxWidth=550',
            title: 'V40 ThinQ™',
            description: 'Take perfect shots of great moments with this unlocked LG V40 ThinQ smartphone. Triple rear cameras automatically provide standard, super-wide-angle and telephoto zoom versions of a captured image, and the AI Cam and AI Composition features let you shoot artistic photos. Compose flattering selfies and group shots with the dual front cameras of this 64GB LG V40 ThinQ smartphone.',
            color: 'Aurora Black',
            price: '$849.99',
            seller: 'LG',
        },
        {
            id: '5',
            image: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6092/6092438_sd.jpg;maxHeight=640;maxWidth=550',
            title: 'Nokia 3310',
            description: 'Connect with family and friends by using this unlocked Nokia cell phone. The 128MB flash storage holds important notes, and the MicroSD slot supports up to 32GB for storing pictures and files. This Nokia cell phone has an extended battery life with up to 22 hours of talk time, so it`s great for travel.',
            color: 'Charcoal',
            price: '$9.99',
            seller: 'Nokia',
        },
    ],
};